"@startuml Length_extension_attack_against_MD4_keyed_MAC_sequence_diagram"

actor Attacker

participant "Attacker" as A
participant "MessageExtractionFacility" as MEF
participant "Server" as S
participant "MD4" as MD4

A -> A : lengthExtensionAttackAtMD4()
activate A

A -> A : extractMessage()
activate A
A --> A : return message
deactivate A

A -> MEF : parseMessage(message, _debugFlag)
activate MEF
MEF --> A : MessageParsed
deactivate MEF

A -> A : computeMD4padding(msgParsed._msg)
activate A
A --> A : return padded message
deactivate A

A -> A : tamperMessageTry(msgParsed)
activate A

A -> MEF : hexToBytes(msgParsed._mac)
activate MEF
MEF --> A : macByteFormat
deactivate MEF

A -> A : extractionMD4InternalState(macByteFormat)
activate A
A --> A : return md4InternalState
deactivate A

loop keyLength = 1 to maxKeySize
    A -> MD4 : hash(appendMessageGoalV, a, b, c, d, messageSize)
    activate MD4
    MD4 --> A : newMac
    deactivate MD4
    
    A -> S : validateMac(newMessage, newMac)
    activate S
    S -> S: Prepend server key to the message    
    S -> MD4: hash(key || newMessage)
    activate MD4
    MD4 --> S: hashServer
    deactivate MD4
    S -> S: Check if hashServer == newMac 
    S --> A : serverReply
    deactivate S
    
    alt serverReply is true
        A -> A : break loop and return true
    end
end

A --> A : return false (if no keyLength found)
deactivate A

@enduml