name: Clang Format Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          FILES=$(find . -type f \( -name "*.cpp" -o -name "*.hpp" \))
          clang-format --dry-run --Werror $FILES

