name: C++ Unit Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ ninja-build

      - name: Find and Build CMake Projects
        run: |
          for dir in $(find . -name 'CMakeLists.txt' -exec dirname {} \;); do
            echo "Building in $dir"
            mkdir -p $dir/build
            cmake -S $dir -B $dir/build -G Ninja -DCMAKE_BUILD_TYPE=Debug
            cmake --build $dir/build
          done

      - name: Run Tests
        run: |
          for test_bin in $(find . -path '*/build/*' -executable -type f); do
            if $test_bin --gtest_list_tests > /dev/null 2>&1; then
              echo "Running tests in $test_bin"
              $test_bin
            fi
          done

