name: C++ Static Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-tidy cppcheck  libgtest-dev libssl-dev nlohmann-json3-dev

      - name: Run Static Code Analysis
        run: |
          echo "🔍 Searching for CMakeLists.txt files..."

          # Find all directories containing a CMakeLists.txt file, excluding 'build' directories and everything inside them
          find . -type f -name "CMakeLists.txt" ! -path "*/build/*" | while read cmake_file; do
              dir=$(dirname "$cmake_file")
              src_dir="$dir/src"
              
              # Run Clang-Tidy only if a src/ folder exists
              if [ -d "$src_dir" ]; then
                  echo "🚀 Running Clang-Tidy in $src_dir"
                  for file in "$src_dir"/*.cpp; do
                      [ -f "$file" ] && clang-tidy "$file" -- -I"$src_dir"
                  done
              fi

              # Run Clang-Tidy on cpp files in the 'tests' folder as well
              if [ -d "$dir/tests" ]; then
                  echo "🚀 Running Clang-Tidy in $dir/tests"
                  for file in "$dir/tests"/*.cpp; do
                      [ -f "$file" ] && clang-tidy "$file" -- -I"$dir/tests"
                  done
              fi

              # Run Cppcheck only if a src/ folder exists
              if [ -d "$src_dir" ]; then
                  echo "🚀 Running Cppcheck in $src_dir"
                  cppcheck --enable=all --inconclusive --force --error-exitcode=1 "$src_dir" --suppress=missingIncludeSystem
              fi

              # Run Cppcheck only if a src/ folder exists
              if [ -d "$src_dir" ]; then
                  echo "🚀 Running Cppcheck in $src_dir"
                  [ -f "$file" ] && cppcheck --enable=all --inconclusive --force --error-exitcode=1 "$src_dir" --suppress=missingIncludeSystem
              fi

              # Run Cppcheck only if a tests/ folder exists
              if [ -d "$dir/tests" ]; then
                  tst_dir="$dir/tests"
                  echo "🚀 Running Cppcheck in $tst_dir"
                  
                  find "$tst_dir" -type f -name "*.cpp" ! -path "*/build/*" | while read file; do
                      cppcheck --enable=all --inconclusive --force --error-exitcode=1 --suppress=missingIncludeSystem --suppress=unusedStructMember --suppress=unusedFunction --suppress=unmatchedSuppression "$file"
                  done
              fi

          done

          echo "✅ Static analysis completed."
          