name: C++ Static Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-tidy cppcheck

      - name: Run Clang-Tidy
        run: |
          find . -type f -name "CMakeLists.txt" | while read cmake_file; do
            dir=$(dirname "$cmake_file")
            src_dir="$dir/src"
            if [ -d "$src_dir" ]; then
              echo "Running Clang-Tidy in $src_dir"
              for file in "$src_dir"/*.cpp; do
                [ -f "$file" ] && clang-tidy "$file" -- -I"$src_dir"
              done
            fi
          done

      - name: Run Cppcheck
        run: |
          find . -type f -name "CMakeLists.txt" | while read cmake_file; do
            dir=$(dirname "$cmake_file")
            echo "Running Cppcheck in $dir"
            cppcheck --enable=all --inconclusive --force --error-exitcode=1 "$dir"
          done
